drive.trajectorySequenceBuilder(new Pose2d(-35.00, 63.00, 0))
.lineToConstantHeading(new Vector2d(-12.00, 60.00))
.lineToConstantHeading(new Vector2d(-12.00, 23.0))
.lineToLinearHeading(new Pose2d(-12.00, 12, Math.toRadians(0)))
.lineToLinearHeading(new Pose2d(-55.00, 12, Math.toRadians(180)))
.lineToLinearHeading(new Pose2d(-24.00, 12, Math.toRadians(270)))
.lineToLinearHeading(new Pose2d(-35.50, 12, Math.toRadians(90)))

initialPosition = [-35, 63, 0];
traj1 = {type = "lineToConstantHeading", args = [[40, -32]], 90]}
traj2 = {type = "lineToConstantHeading", args = [-12, 60]}
traj3 = {type = "linetoLinearHeading"}